const DA0 = [{en:"Many people took the fallen stones to repair houses and churches."},
{en:"The Romans of those days were not connected to the Coliseum."},
{en:"It had last been used as a castle. Before that it was a graveyard."},
{en:"It has been hundreds of years since the games. The damage to the Coliseum was never repaired."},
{en:"It's a good thing the outer wall of it still stands strong."},
{en:"Today the Coliseum is one of Rome's most popular attractions."},
{en:"People from all over the world come to Italy to visit it."},
{en:"The Pope leads a big march around it every Good Friday."},
{en:"Coliseum has become a symbol of Italy that is known to the world today."}
];


const DA2 = [{zh:'許多人撿拾掉落的石頭來修復房子和教堂'},
{zh:'當時的羅馬人與羅馬競技場並無聯繫。'},
{zh:'它最後被用作城堡。在此之前，它是一片墓地。'},
{zh:'距離奧運會已經過去幾百年了，但體育館的損壞一直未能修復'},
{zh:'幸好它的外牆仍然堅固。'},
{zh:'如今，羅馬競技場是羅馬最受歡迎的景點之一'},
{zh:'來自世界各地的人們來到義大利參觀。'},
{zh:'每年耶穌受難日，教宗都會帶領大家圍繞它進行大規模遊行。'},
{zh:'鬥獸場如今已成為世界聞名的義大利的象徵'}
];


const DA1 = [{ en: "Many", zh: "[形]許多的"},
{ en: "people", zh: "[名]人們"},
{ en: "churches", zh: "[名]教堂"},
{ en: "took", zh: "take過去式"},
{ en: "the", zh: "這些，那些"},
{ en: "fallen", zh: "掉落"},
{ en: "stones", zh: "石頭"},
{ en: "to", zh: "[介]向；往；到"},
{ en: "repair", zh: "[vt][名]修理；修補"},
{ en: "houses", zh: "房子"},
{ en: "and", zh: "[連]和"},
{ en: "The", zh: "這些，那些"},
{ en: "Romans", zh: "羅馬"},
{ en: "those", zh: "pro[名][形]那些"},
{ en: "days", zh: "日子"},
{ en: "were", zh: "is過去式"},
{ en: "not", zh: "[副]不"},
{ en: "connected", zh: ""},
{ en: "It", zh: "它"},
{ en: "had", zh: "有"},
{ en: "last", zh: "最後"},
{ en: "been", zh: "be完成式"},
{ en: "used", zh: "[形]舊的"},
{ en: "as", zh: "[介][副][連]當作、如同"},
{ en: "a", zh: "一"},
{ en: "castle", zh: "[名]城堡"},
{ en: "Before", zh: "[介]在…之前"},
{ en: "that", zh: "那"},
{ en: "it", zh: "它"},
{ en: "was", zh: "am過去式"},
{ en: "has", zh: "有"},
{ en: "hundreds", zh: ""},
{ en: "years", zh: "年"},
{ en: "since", zh: "[介][連]此後；因為"},
{ en: "games", zh: "N遊"},
{ en: "damage", zh: "[名][vt]損害"},
{ en: "Coliseum", zh: "[名]體育館"},
{ en: "never", zh: "[副]從不"},
{ en: "It's", zh: ""},
{ en: "good", zh: "[形]好的"},
{ en: "thing", zh: "[名]物品"},
{ en: "outer", zh: "[形]外面的，外表的"},
{ en: "wall", zh: "[名]牆"},
{ en: "still", zh: "[形]靜止的、[副]仍舊"},
{ en: "stands", zh: "站"},
{ en: "Today", zh: "[名]今天"},
{ en: "Rome's", zh: ""},
{ en: "most", zh: "[形][副]pro[名]最多(的)"},
{ en: "popular", zh: "[形]大眾的"},
{ en: "People", zh: "[名]人們"},
{ en: "from", zh: "[介]從"},
{ en: "all", zh: "[形]一切的"},
{ en: "over", zh: "[介]在…之上[副]在上方[形]結束的"},
{ en: "world", zh: "[名]世界"},
{ en: "come", zh: "[vi]來"},
{ en: "Italy", zh: ""},
{ en: "visit", zh: "[vt]參觀"},
{ en: "Pope", zh: ""},
{ en: "leads", zh: ""},
{ en: "big", zh: "[形]大的"},
{ en: "march", zh: "[名]三月(Mar.)"},
{ en: "around", zh: "[副][介]到處"},
{ en: "every", zh: "[形]每個"},
{ en: "Good", zh: "[形]好的"},
{ en: "become", zh: "[vi]成為"},
{ en: "symbol", zh: "[名]象徵"},
{ en: "known", zh: "知道"}
];
