const DA0 = [{en:"Are you tired of losing your glasses or having to clean and care for your contact lenses?"},
{en:"Do you want to improve your appearance without the burden of contacts or getting new glasses ?"},
{en:"Have you ever wanted to participate in a sport or get a job that makes wearing glasses or contacts inconvenient ?"},
{en:"If you have ever considered these questions, perhaps you should think about cosmetic laser eye surgery ."},
{en:"Laser eye surgery moulds your eye by using a laser , a powerful beam of light which cuts the surface of the eye."},
{en:"While the surgery is considered low risk and can be done quickly , there are always possible complications when having any surgery performed ."},
{en:"Most patients will deal with some amount of pain or discomfort for a few days."},
{en:"Blurred vision and sensitivity to light are also common, making it difficult to see properly ."},
{en:"Although these symptoms usually clear up in the days following surgery, for some patients these symptoms may persist for several weeks , months or even continue permanently ."},
{en:"It is important to understand the risks involved when considering surgery ."}
];


const DA2 = [{zh:'您是否厭倦了丟失眼鏡或不得不清潔和護理隱形眼鏡？'},
{zh:'您是否想改善自己的外表，但又不想承受配戴隱形眼鏡或購買新眼鏡的負擔？'},
{zh:'您是否曾經想參加某項運動或找到一份戴眼鏡或隱形眼鏡不方便的工作？'},
{zh:'如果您曾經考慮過這些問題，也許您應該考慮美容雷射眼科手術。'},
{zh:'雷射眼科手術利用雷射（切割眼球表面的強光束）來塑造您的眼睛。'},
{zh:'雖然該手術風險較低且可以快速完成，但任何手術都可能出現併發症。'},
{zh:'大多數患者會在幾天內感到一定程度的疼痛或不適'},
{zh:'視力模糊和對光線的敏感也很常見，導致看不清楚。'},
{zh:'雖然這些症狀通常會在手術後的幾天內消失，但對於某些患者來說，這些症狀可能會持續數週、數月甚至永久持續下去'},
{zh:'當考慮手術時，了解所涉及的風險非常重要。'}
];


const DA1 = [{ en: "Are", zh: ""},
{ en: "contact lenses", zh: "隱形眼鏡",isPhrase: true },
{ en: "clear up", zh: "ph.清理、消失",isPhrase: true },

{ en: "you", zh: "你"},
{ en: "tired", zh: "疲倦的"},
{ en: "of", zh: "的"},
{ en: "losing", zh: "[形]失敗的；[動]丟失"},
{ en: "your", zh: "你的"},
{ en: "glasses", zh: "[名]眼鏡"},
{ en: "or", zh: "或"},
{ en: "having", zh: "有"},
{ en: "to", zh: "[介]向；往；到"},
{ en: "clean", zh: "[形]乾淨的"},
{ en: "and", zh: "[連]和"},
{ en: "care", zh: "[vi]關心"},
{ en: "for", zh: "[介]為了"},
{ en: "contact", zh: "[名][動]接觸。[形]接觸的"},
{ en: "Do", zh: "[vt]做"},
{ en: "want", zh: "[vt]想要"},
{ en: "improve", zh: "[動]改進，改善；增進"},
{ en: "appearance", zh: "[名]顯露"},
{ en: "without", zh: "[介][副]沒有"},
{ en: "the", zh: "這些，那些"},
{ en: "burden", zh: "[名]重擔；負擔"},
{ en: "contacts", zh: "暗指→隱形眼鏡"},
{ en: "getting", zh: ""},
{ en: "new", zh: "[形]新的"},
{ en: "Have", zh: "[vt]擁有"},
{ en: "ever", zh: "[副]從來"},
{ en: "wanted", zh: "想要"},
{ en: "participate", zh: "[vi]參加，參與[(+in)]"},
{ en: "in", zh: "在"},
{ en: "a", zh: "一"},
{ en: "sport", zh: "[名]運動"},
{ en: "get", zh: "[vt]獲得"},
{ en: "job", zh: "工作"},
{ en: "that", zh: "那"},
{ en: "makes", zh: "製作"},
{ en: "wearing", zh: "戴"},
{ en: "inconvenient", zh: "不方便"},
{ en: "If", zh: "如果"},
{ en: "have", zh: "[vt]擁有"},
{ en: "considered", zh: "考慮"},
{ en: "these", zh: "pro[名][形]這些"},
{ en: "questions", zh: "問題"},
{ en: "perhaps", zh: "[副]大概"},
{ en: "should", zh: "應該"},
{ en: "think", zh: "[vi][vt]想"},
{ en: "about", zh: "[介]關於"},
{ en: "cosmetic", zh: "[形]化妝用的"},
{ en: "laser", zh: "[名]雷射"},
{ en: "eye", zh: "[名]眼睛"},
{ en: "surgery", zh: "[名]外科，(外科)手術；手術室"},
{ en: "Laser", zh: "[名]雷射"},
{ en: "moulds", zh: "模具"},
{ en: "by", zh: "[介]透過；在…旁邊"},
{ en: "using", zh: "[動]使用。use的動詞現在分詞、動名詞"},
{ en: "powerful", zh: "[形]強大的"},
{ en: "beam", zh: "[名]笑容，喜色[vt]流露；發出[vi]眉開眼笑"},
{ en: "light", zh: "[名]光[vt][vi]照亮[形]明亮的、[形]淺色的；輕的"},
{ en: "which", zh: "pro[名]哪一個"},
{ en: "cuts", zh: "切"},
{ en: "surface", zh: "[名]表面"},
{ en: "While", zh: "[連]當…時；然而、[名]一會兒、[vt]消磨(時光)"},
{ en: "is", zh: "是"},
{ en: "low", zh: "[形]低的"},
{ en: "risk", zh: "[名]危險，風險[vt]冒…的風險[+V-ing]"},
{ en: "can", zh: "[助]可以、[名]罐頭"},
{ en: "be", zh: ""},
{ en: "done", zh: "做"},
{ en: "quickly", zh: "迅速地"},
{ en: "there", zh: "[副][名](在)那裡int.好啦!"},
{ en: "are", zh: ""},
{ en: "always", zh: "[副]總是"},
{ en: "possible", zh: "[形]可能的"},
{ en: "complications", zh: "併發症"},
{ en: "when", zh: "[副][連]pro[名]何時"},
{ en: "any", zh: "[形]任何的"},
{ en: "performed", zh: "執行"},
{ en: "Most", zh: "[形][副]pro[名]最多(的)"},
{ en: "patients", zh: "患者"},
{ en: "will", zh: "[名]意志；遺囑、[助]將"},
{ en: "deal", zh: "[vi]處理"},
{ en: "with", zh: "prpe.與…一起"},
{ en: "some", zh: "[形]某些"},
{ en: "amount", zh: "[名]數量"},
{ en: "pain", zh: "[名]疼痛"},
{ en: "discomfort", zh: "[名]不舒適"},
{ en: "few", zh: "[形]很少的"},
{ en: "Blurred", zh: "[形]模糊不清的。[動]弄髒、變模糊"},
{ en: "vision", zh: "[名]視力；視覺；洞察力，眼光"},
{ en: "sensitivity", zh: "[名]敏感"},
{ en: "also", zh: "[副]也"},
{ en: "common", zh: "[形]普通的"},
{ en: "making", zh: "製作"},
{ en: "it", zh: "它"},
{ en: "difficult", zh: "[形]困難的"},
{ en: "see", zh: "[vt]看見"},
{ en: "properly", zh: "[副]恰當地；正確地；有禮貌地"},
{ en: "Although", zh: "[連]儘管"},
{ en: "symptoms", zh: "症狀"},
{ en: "usually", zh: "通常"},
{ en: "clear", zh: "[形]清晰的"},
{ en: "up", zh: "[副]向上"},
{ en: "days", zh: "日子"},
{ en: "following", zh: "[形]接著的"},
{ en: "may", zh: "[名]五月"},
{ en: "persist", zh: "[vi][vt]堅持(說)"},
{ en: "several", zh: "[形]幾個的"},
{ en: "weeks", zh: "週"},
{ en: "months", zh: "月"},
{ en: "even", zh: "(1)[副]甚至、[形]偶數的"},
{ en: "continue", zh: "[vi]繼續"},
{ en: "permanently", zh: "永久地"},
{ en: "It", zh: "它"},
{ en: "important", zh: "[形]重要的"},
{ en: "understand", zh: "[vt]理解"},
{ en: "risks", zh: "危險"},
{ en: "involved", zh: "[形]複雜的。[動]包含"},
{ en: "considering", zh: "考慮"}
];
