// 英文文章数组
const DA0 = [{en:'The put on Coliseum is an ancient stadium in the center of Rome.'},
{en:'Gruesome games where men fought against lions, tigers, and bears took place in it.'},
{en:'These games were dreadful, but most of the people loved it.'},
{en:'The Coliseum has been damaged many times over the years.'},
{en:'It was struck by lightning in the year 217, and this caused a fire.'},
{en:'Much of the Coliseum is made of stone. But the fire damaged the upper levels which were made of wood.'},
{en:'This damage took many years to repair.'},
{en:'The worst damage happened in 1349.'},
{en:'A mighty earthquake shook Rome and the Coliseum.'},
{en:'The south side of the building collapse.'},
{en:'Pieces of the arena were all over the ground.'}
];

const DA2 = [{zh:'羅馬競技場是位於羅馬市中心的一座古老體育場。'},
{zh:'這裡舉行了人類與獅子、老虎和熊搏鬥的殘酷遊戲'},
{zh:'這些遊戲很糟糕，但大多數人都喜歡它。'},
{zh:'多年來，羅馬競技場曾多次遭到破壞。'},
{zh:'公元 217 年，它被雷擊中，並引發火災'},
{zh:'鬥獸場的大部分結構都是由石頭建造的。但火災損壞了木頭建造的上層建築。'},
{zh:'這項損害花了很多年才得以修復'},
{zh:'最嚴重的破壞發生在1349年'},
{zh:'一場強烈的地震震撼了羅馬和羅馬競技場'},
{zh:'建築物南側倒塌。'},
{zh:'競技場的碎片散落在地面上'}
];

const DA1 = [{ en: 'The', zh: '這些，那些'},
{ en: "put on", zh: "穿", isPhrase: true },
{ en: "took place", zh: "發生", isPhrase: true },
{ en: 'Coliseum', zh: '[名]體育館'},
{ en: 'collapse', zh: '坍塌'},
{ en: 'is', zh: '是'},
{ en: 'an', zh: '一'},
{ en: 'ancient', zh: '[形]古代的'},
{ en: 'stadium', zh: '[名]體育場，運動場'},
{ en: 'in', zh: '在'},
{ en: 'the', zh: '這些，那些'},
{ en: 'center', zh: '[名]中心'},
{ en: 'of', zh: '的'},
{ en: 'Gruesome', zh: '[名]體育館'},
{ en: 'games', zh: '[名]遊戲'},
{ en: 'where', zh: '[副][連][代]在哪裡'},
{ en: 'men', zh: '男人'},
{ en: 'fought', zh: '[動]打'},
{ en: 'against', zh: '[介]反對'},
{ en: 'lions', zh: '[名]獅'},
{ en: 'tigers', zh: '[名]老虎'},
{ en: 'and', zh: '[連]和'},
{ en: 'bears', zh: '[名]熊'},
{ en: 'took', zh: '[動]take過去式'},
{ en: 'place', zh: '[名]地方'},
{ en: 'These', zh: '[代][形]這些'},
{ en: 'were', zh: 'is過去式'},
{ en: 'dreadful', zh: '[形]畏懼的；可怕的'},
{ en: 'but', zh: '[連]但是'},
{ en: 'most', zh: '[形][副][代]最多(的)'},
{ en: 'people', zh: '[名]人們'},
{ en: 'loved', zh: '愛'},
{ en: 'has', zh: '有'},
{ en: 'been', zh: 'be 完成式'},
{ en: 'damaged', zh: '損壞的'},
{ en: 'many', zh: '[形]許多的'},
{ en: 'times', zh: '時間'},
{ en: 'over', zh: '[介]在…之上[副]在上方[形]結束的'},
{ en: 'It', zh: '它'},
{ en: 'was', zh: 'am過去式'},
{ en: 'struck', zh: ''},
{ en: 'by', zh: '[介]透過；在…旁邊'},
{ en: 'lightning', zh: '[名]閃電'},
{ en: 'year', zh: '[名]年'},
{ en: '217', zh: ''},
{ en: 'this', zh: '[代][形]這個'},
{ en: 'caused', zh: '造成'},
{ en: 'a', zh: '一'},
{ en: 'Much', zh: '[形][副][代]許多(的)'},
{ en: 'made', zh: '製作 make過去式'},
{ en: 'stone', zh: '[名]石頭'},
{ en: 'But', zh: '[連]但是'},
{ en: 'fire', zh: '[名]火、[vt][vi]開火、[vt]開除'},
{ en: 'upper', zh: '[形]上面的'},
{ en: 'levels', zh: ''},
{ en: 'which', zh: '[代]哪一個'},
{ en: 'This', zh: '[代][形]這個'},
{ en: 'damage', zh: '[名][vt]損害'},
{ en: 'years', zh: '[名]年'},
{ en: 'to', zh: '[介]向；往；到'},
{ en: 'worst', zh: '[形]最壞的'},
{ en: 'happened', zh: ''},
{ en: 'A', zh: '一'},
{ en: 'mighty', zh: 'a.強大的；強有力的'},
{ en: 'earthquake', zh: 'n.地震'},
{ en: 'shook', zh: ''},
{ en: 'Rome', zh: ''},
{ en: 'south', zh: '[名]南'},
{ en: 'side', zh: '[名]邊；面'},
{ en: 'building', zh: '[名]建築物'},
{ en: 'Pieces', zh: ''},
{ en: 'arena', zh: '[名]競技場'},
{ en: 'all', zh: '[形]一切的'}
];
