const DA0 = [{en:"Americans are famous for dieting."},
{en:"They spend a lot of money on food, but then spend much more on exercise and diet programs that help them remove their extra pounds."},
{en:"It is true that Americans put too much emphasis on the perfect body, so that many people who are only slightly overweight feel that they are fat and ugly."},
{en:"Doctors agree that such a bad self-image is actually more harmful to the health than a little extra weight."},
{en:"It is also true that many of the weight-loss programs are only tricks; people spend their money needlessly on secret methods for losing weight quickly, but such programs rarely work and often are unhealthy."},
{en:"However, the American concern about being overweight is not just a matter of fashion."},
{en:"Fatness can cause serious health problems, and among them is the number one killer of Americans: heart disease."},
{en:"There is really only one way to lose weight: exercise regularly and eat less."},
{en:"Of course, when eating less, it becomes extremely important to choose proper foods."},
{en:"Foods that are fried and have high concentrations of fat, such as hamburgers, must be avoided in favor of vegetables and fruit."}
];


const DA2 = [{zh:'美國人以節食聞名。'},
{zh:'他們在食物上花費很多錢，但在幫助他們減掉多餘體重的運動和節食計劃上花費更多'},
{zh:'確實，美國人過於強調完美的身材，以致許多體重只是稍微超重的人都覺得自己又胖又醜。'},
{zh:'醫生們一致認為，這種糟糕的自我形像其實比體重增加對健康的傷害更大'},
{zh:'許多減肥計劃確實只是一些花招；人們不必要地花錢購買快速減肥的秘密方法，但這樣的計劃很少有效，而且往往不健康。'},
{zh:'然而，美國人對於體重超重的擔憂並不僅僅是出於時尚考量'},
{zh:'肥胖會導致嚴重的健康問題，其中包括美國人的頭號殺手：心臟病'},
{zh:'減肥其實只有一種方法：經常運動並且少吃。'},
{zh:'當然，在少吃的時候，選擇合適的食物就變得極為重要'},
{zh:'必須避免食用漢堡等油炸和高脂肪食物，而應多吃蔬菜和水果'}
];


const DA1 = [
{ en: "Americans", zh: "美國"},
{ en: "are", zh: "是"},
{ en: "famous", zh: "[形]著名的"},
{ en: "for", zh: "[介]為了"},
{ en: "They", zh: "pro[名]他們"},
{ en: "spend", zh: "[vt]花費"},
{ en: "a", zh: "一"},
{ en: "lot", zh: "[名]很多；籤；一塊地"},
{ en: "of", zh: "的"},
{ en: "money", zh: "[名]錢"},
{ en: "on", zh: ""},
{ en: "food", zh: "[名]食物"},
{ en: "but", zh: "[連]但是"},
{ en: "then", zh: "[副][名]那時"},
{ en: "much", zh: "[形][副]pro[名]許多(的)"},
{ en: "more", zh: "[形][副]pro[名]更多(的)"},
{ en: "exercise", zh: "v.[名]運動"},
{ en: "and", zh: "[連]和"},
{ en: "diet", zh: "[名]節食；飲食"},
{ en: "programs", zh: "計畫、程序"},
{ en: "that", zh: "那"},
{ en: "help", zh: "協助"},
{ en: "them", zh: "pro[名]他們"},
{ en: "remove", zh: "[vt][vi]移動，搬開；去掉，消除"},
{ en: "their", zh: "他們的"},
{ en: "extra", zh: "[形]額外的"},
{ en: "It", zh: "它"},
{ en: "is", zh: "是"},
{ en: "true", zh: "[形]真實的"},
{ en: "put", zh: "[vt]放"},
{ en: "too", zh: "[副]也"},
{ en: "emphasis", zh: "[名]強調，重視，重點"},
{ en: "the", zh: "這些，那些"},
{ en: "perfect", zh: "[形]完美的"},
{ en: "body", zh: "[名]身體"},
{ en: "so", zh: "所以"},
{ en: "many", zh: "[形]許多的"},
{ en: "people", zh: "[名]人們"},
{ en: "who", zh: "pro[名]誰"},
{ en: "only", zh: "[形]唯一的"},
{ en: "slightly", zh: "[副]輕微地；稍微地"},
{ en: "overweight", zh: "超重"},
{ en: "feel", zh: "[名][vt]觸摸；感覺"},
{ en: "they", zh: "pro[名]他們"},
{ en: "fat", zh: "[形]肥胖的"},
{ en: "Doctors", zh: "醫師"},
{ en: "agree", zh: "[vi]同意"},
{ en: "such", zh: "[形]如此的"},
{ en: "bad", zh: "[形]壞的"},
{ en: "self-image", zh: "自我形象；自我定位"},
{ en: "actually", zh: "實際上"},
{ en: "harmful", zh: "[形]有害的[(+to)]"},
{ en: "to", zh: "[介]向；往；到"},
{ en: "health", zh: "[名]健康"},
{ en: "than", zh: "[連]比[介]超過"},
{ en: "little", zh: "[形]小的[副]少"},
{ en: "also", zh: "[副]也"},
{ en: "weight-loss", zh: "[名]重量損失；失重"},
{ en: "tricks;", zh: "騙局；謀略；"},
{ en: "needlessly", zh: "[副]不必要地；無用地"},
{ en: "secret", zh: "[形]祕密的"},
{ en: "methods", zh: ""},
{ en: "losing", zh: ""},
{ en: "weight", zh: "[名]重量"},
{ en: "quickly", zh: "迅速地"},
{ en: "rarely", zh: "很少"},
{ en: "work", zh: "[名][vi][vt]工作"},
{ en: "often", zh: "[副]常常"},
{ en: "However", zh: "[副]然而"},
{ en: "American", zh: ""},
{ en: "concern", zh: "[vt]關於；關心[名]關心"},
{ en: "about", zh: "[介]關於"},
{ en: "being", zh: "[名]存在，生命；生物"},
{ en: "not", zh: "[副]不"},
{ en: "just", zh: ""},
{ en: "matter", zh: "[名]事件、[vi]重要"},
{ en: "Fatness", zh: "[名]肥胖；多脂肪"},
{ en: "can", zh: "[助]可以、[名]罐頭"},
{ en: "cause", zh: "[名]原因"},
{ en: "serious", zh: "[形]嚴重的"},
{ en: "problems", zh: ""},
{ en: "among", zh: "[介]在…之中"},
{ en: "number", zh: "[名]數字"},
{ en: "one", zh: "[名]一"},
{ en: "killer", zh: ""},
{ en: "Americans:", zh: ""},
{ en: "heart", zh: "[名]心臟"},
{ en: "There", zh: "[副][名](在)那裡int.好啦!"},
{ en: "really", zh: ""},
{ en: "way", zh: "[名]路"},
{ en: "lose", zh: "[vt][vi]丟失"},
{ en: "weight:", zh: "重量"},
{ en: "regularly", zh: "[副]有規律地；定期地"},
{ en: "eat", zh: "[vt]吃"},
{ en: "Of", zh: "的"},
{ en: "course", zh: "[名]路線"},
{ en: "when", zh: "[副][連]pro[名]何時"},
{ en: "eating", zh: "吃"},
{ en: "less", zh: "少"},
{ en: "it", zh: "它"},
{ en: "becomes", zh: "變成"},
{ en: "extremely", zh: "[副]極端地；極其；非常"},
{ en: "important", zh: "重要的"},
{ en: "choose", zh: "[vt][vi]挑選"},
{ en: "proper", zh: "[形]適合的，適當的"},
{ en: "Foods", zh: "食物"},
{ en: "fried", zh: "油炸的，油煎的"},
{ en: "have", zh: "[vt]擁有"},
{ en: "high", zh: "高"},
{ en: "concentrations", zh: ""},
{ en: "as", zh: "[介][副][連]當作、如同"},
{ en: "hamburgers", zh: ""},
{ en: "must", zh: "[助]必須"},
{ en: "avoided", zh: "避免"},
{ en: "in", zh: "在"},
{ en: "favor", zh: "[名][vt]贊成"},
{ en: "vegetables", zh: "蔬菜"}
];
