const DA0 = [{en:"I once had a patient who was so sleep-deprived that she loaded her."},
{en:"dirty dishes into the clothes dryer instead of the dishwasher."},
{en:"She turned on the machine, smashing china and glasses."},
{en:"Another patient went to great lengths to obtain a prime-spot ticket to a football game, but was so sleepy that he dozed off in his seat in the early minutes of play and remained asleep until the match ended."},
{en:"On an everyday level, sleepy people make mathematics errors, break things and become cross with their families, friends and colleagues."},
{en:"Less commonly, they make mistakes with tragic consequences."},
{en:"It is hard to prove how many fatal car accidents are caused by the driver's falling asleep at the wheel, but my conviction is that the number is high."}
];


const DA2 = [{zh:'我曾經有一個病人，她睡眠嚴重不足，所以她裝了東西給她。'},
{zh:'將髒盤子放入乾衣機而不是洗碗機'},
{zh:'她打開機器，打破了瓷器和玻璃器皿。'},
{zh:'另一位病人費了好大勁才拿到一張足球比賽的黃金位置門票，但是他太困了，比賽剛開始幾分鐘他就在座位上打起了瞌睡，一直睡到比賽結束'},
{zh:'在日常生活中，困倦的人會犯數學錯誤、破壞東西，並對家人、朋友和同事發脾氣。'},
{zh:'不太常見的是，他們會犯錯並造成悲慘的後果'},
{zh:'很難證明有多少起致命車禍是因為司機睡著造成的，但我確信這個數字很高'}
];


const DA1 = [{ en: "I", zh: ""},
{ en: "once", zh: "[副]一次；一旦"},
{ en: "had", zh: "有"},
{ en: "a", zh: "一"},
{ en: "patient", zh: "[形]有耐心的、[名]病人"},
{ en: "who", zh: "pro[名]誰"},
{ en: "was", zh: "am過去式"},
{ en: "so", zh: ""},
{ en: "sleep-deprived", zh: ""},
{ en: "that", zh: "那"},
{ en: "she", zh: "pro[名](主格)她"},
{ en: "loaded", zh: ""},
{ en: "dirty", zh: "[形]髒的"},
{ en: "dishes", zh: "[名]碟"},
{ en: "into", zh: ""},
{ en: "the", zh: "這些，那些"},
{ en: "clothes", zh: "[名]服裝"},
{ en: "dryer", zh: "[名]烘乾機"},
{ en: "instead", zh: "[副]反而，卻"},
{ en: "of", zh: "的"},
{ en: "She", zh: "pro[名](主格)她"},
{ en: "turned", zh: "轉身"},
{ en: "on", zh: ""},
{ en: "machine", zh: "[名]機器"},
{ en: "smashing", zh: "[形]猛烈的、[vi][vt]粉碎；打碎。Smash的動詞現在分詞、動名詞"},
{ en: "china", zh: "[名]瓷器、中國"},
{ en: "and", zh: "[連]和"},
{ en: "Another", zh: "[形]另外的"},
{ en: "went", zh: ""},
{ en: "to", zh: "[介]向；往；到"},
{ en: "great", zh: "[形]極好的"},
{ en: "lengths", zh: ""},
{ en: "obtain", zh: "[vt]得到，獲得"},
{ en: "prime-spot", zh: ""},
{ en: "ticket", zh: "[名]票"},
{ en: "football", zh: "[名]橄欖球；足球"},
{ en: "game", zh: "[名]遊戲"},
{ en: "but", zh: "[連]但是"},
{ en: "sleepy", zh: "[形]想睡的"},
{ en: "he", zh: "[名]他"},
{ en: "dozed", zh: "[vi][名]打瞌睡。Doze的動詞過去式、過去分詞"},
{ en: "off", zh: "[副][介][形]離開(…)"},
{ en: "in", zh: "在"},
{ en: "his", zh: ""},
{ en: "seat", zh: "[名]座位"},
{ en: "early", zh: "[形]早的"},
{ en: "minutes", zh: ""},
{ en: "play", zh: "[vi]玩耍"},
{ en: "remained", zh: "[vi]剩下；保持。Remain的動詞過去式、過去分詞"},
{ en: "asleep", zh: "[形]睡著的"},
{ en: "until", zh: "[介]直到…為止(till)"},
{ en: "match", zh: "、[vt][vi]相配[名]比賽"},
{ en: "On", zh: ""},
{ en: "an", zh: "一"},
{ en: "everyday", zh: ""},
{ en: "level", zh: ""},
{ en: "people", zh: "[名]人們"},
{ en: "make", zh: "[vt]做"},
{ en: "mathematics", zh: "[名]數學(math)"},
{ en: "errors", zh: "[名]失誤"},
{ en: "break", zh: "[vt]打破"},
{ en: "things", zh: ""},
{ en: "become", zh: "[vi]成為"},
{ en: "cross", zh: "[名]十字形[vt]vi橫越[形]發怒的"},
{ en: "with", zh: "prpe.與…一起"},
{ en: "their", zh: ""},
{ en: "families", zh: ""},
{ en: "friends", zh: ""},
{ en: "Less", zh: ""},
{ en: "commonly", zh: "[副]通常地，一般地；"},
{ en: "they", zh: "pro[名]他們"},
{ en: "mistakes", zh: "錯誤"},
{ en: "tragic", zh: "[形]悲劇的；悲慘的，不幸的"},
{ en: "It", zh: "它"},
{ en: "is", zh: "是"},
{ en: "hard", zh: "[形]堅硬的[副]努力地"},
{ en: "prove", zh: "[vt]證明"},
{ en: "how", zh: ""},
{ en: "many", zh: "[形]許多的"},
{ en: "fatal", zh: "[形]命運的；致命的，生死攸關的"},
{ en: "car", zh: "[名]汽車"},
{ en: "accidents", zh: "[名]意外；災禍。Accident的名詞複數"},
{ en: "are", zh: ""},
{ en: "caused", zh: "[V]造成"},
{ en: "by", zh: "[介]透過；在…旁邊"},
{ en: "driver's", zh: ""},
{ en: "falling", zh: ""},
{ en: "at", zh: "[介]在…地點"},
{ en: "wheel", zh: "[名]輪子"},
{ en: "my", zh: "pro[名]我的"},
{ en: "conviction", zh: "[名]定罪；信念"},
{ en: "number", zh: "[名]數字"}
];
