const DA0 = [
{en:"American public and private agencies spend millions of dollars annually attempting to persuade citizens to drink alcohol only in 'moderate' amounts or not at all, particularly when operating a motor vehicle."},
{en:"Studies indicate that this propaganda and advertising approach is almost totally ineffective ."},
{en:"Alcohol consumption continues to rise nationally, and alcohol-related traffic deaths, especially for teenage drivers, have increased ."},
{en:"In contrast to the American approach, Norway has severe, but meaningful, penalties for driving while drunk."},
{en:"These include periods of compulsory public work(picking up trash along highways), mandatory jail sentences that do not interfere with one's work (a member of the Norwegian royal family will be equally punished if guilty )."},
{en:"As a result, many Norwegians use taxis or the drivers not drinking when spending a night on the town."}];

const DA2 = [
{zh:'美國公共和私人機構每年花費數百萬美元試圖勸說公民只「適量」飲酒或根本不飲酒，特別是在駕駛機動車輛時'},
{zh:'研究表明，這種宣傳和廣告方式幾乎完全無效'},
{zh:'全國的酒精消費量持續上升，與酒精有關的交通死亡人數（尤其是青少年駕駛者的死亡人數）也有所增加'},
{zh:'與美國的做法相反，挪威對酒後駕駛的處罰嚴厲但有意義'},
{zh:'這些措施包括強制公共工作（在高速公路沿線撿垃圾）、不影響工作的強制監禁（挪威王室成員如果有罪也將受到同樣的懲罰）'},
{zh:'因此，許多挪威人在城裡過夜時會搭乘計程車或司機不喝酒'}];

const DA1 = [{ en: "American", zh: ""},

{ en: "alcohol-related", zh: "酒精有關"},
{ en: "public", zh: "[形]公眾的"},
{ en: "and", zh: "[連]和"},
{ en: "private", zh: "[形]私人的"},
{ en: "agencies", zh: "機構"},
{ en: "spend", zh: "[vt]花費"},
{ en: "millions", zh: "百萬"},
{ en: "of", zh: "的"},
{ en: "dollars", zh: "[名]元"},
{ en: "annually", zh: "每年"},
{ en: "attempting", zh: "嘗試"},
{ en: "to", zh: "[介]向；往；到"},
{ en: "persuade", zh: "[vt]說服，勸服"},
{ en: "citizens", zh: "國民"},
{ en: "drink", zh: "[vt]喝"},
{ en: "alcohol", zh: "[名]酒精；含酒精飲料；酒"},
{ en: "only", zh: "[形]唯一的"},
{ en: "in", zh: "在"},
{ en: "amounts", zh: "金額"},
{ en: "or", zh: "或"},
{ en: "not", zh: "[副]不"},
{ en: "at", zh: "[介]在…地點"},
{ en: "all", zh: "[形]一切的"},
{ en: "particularly", zh: "特別"},
{ en: "when", zh: "[副][連]pro[名]何時"},
{ en: "operating", zh: "操作"},
{ en: "a", zh: "一"},
{ en: "motor", zh: "[名]馬達，發動機"},
{ en: "vehicle", zh: "[名]運載工具；車輛"},
{ en: "indicate", zh: "[vt]指出"},
{ en: "that", zh: "那"},
{ en: "this", zh: "pro[名][形]這個"},
{ en: "propaganda", zh: "[名]宣傳"},
{ en: "advertising", zh: "廣告"},
{ en: "approach", zh: "v.接近，靠近[名]方法"},
{ en: "is", zh: "是"},
{ en: "almost", zh: "[副]幾乎"},
{ en: "ineffective", zh: "無效"},
{ en: "Alcohol", zh: "[名]酒精；含酒精飲料；酒"},
{ en: "consumption", zh: "[名]消耗"},
{ en: "continues", zh: "繼續"},
{ en: "rise", zh: "[vi]上升"},
{ en: "nationally", zh: "全國範圍內"},
{ en: "traffic", zh: "[名]交通"},
{ en: "deaths", zh: "死亡數"},
{ en: "especially", zh: "[副]尤其"},
{ en: "for", zh: "[介]為了"},
{ en: "teenage", zh: "[名]青少年時期"},
{ en: "drivers", zh: "[名]司機"},
{ en: "have", zh: "[vt]擁有"},
{ en: "increased", zh: "[動][名]增加"},
{ en: "In", zh: "在"},
{ en: "contrast", zh: "[名]對比，對照[vi][kənˋtræst][vt]使對比，使對照"},
{ en: "the", zh: "這些，那些"},
{ en: "has", zh: "有"},
{ en: "severe", zh: "[形]嚴重的；劇烈的；嚴厲的；嚴肅的"},
{ en: "but", zh: "[連]但是"},
{ en: "meaningful", zh: "[形]有意義的；意味深長的"},
{ en: "penalties", zh: "處罰"},
{ en: "while", zh: "[連]當…時；然而、[名]一會兒、[vt]消磨(時光)"},
{ en: "These", zh: "pro[名][形]這些"},
{ en: "include", zh: "[vt]包含"},
{ en: "periods", zh: "期間"},
{ en: "compulsory", zh: "強制性的"},
{ en: "up", zh: "[副]向上"},
{ en: "trash", zh: "[名]廢物，垃圾"},
{ en: "along", zh: "[介]沿著"},
{ en: "mandatory", zh: "強制的"},
{ en: "jail", zh: "[名]監獄；拘留所[vt]監禁"},
{ en: "sentences", zh: "句子"},
{ en: "do", zh: "[vt]做"},
{ en: "interfere", zh: "[vt][vi]妨礙；衝突[(+with)]"},
{ en: "with", zh: "prpe.與…一起"},
{ en: "one's", zh: ""},
{ en: "work", zh: "[名][vi][vt]工作"},
{ en: "member", zh: "[名]成員"},
{ en: "royal", zh: "[形]王室的"},
{ en: "family", zh: "[名]家庭"},
{ en: "will", zh: "[名]意志；遺囑、[助]將"},
{ en: "be", zh: ""},
{ en: "equally", zh: "[副]相同地；同樣地"},
{ en: "punished", zh: "受到懲罰"},
{ en: "if", zh: "如果"},
{ en: "guilty", zh: "[形]有罪的，犯…罪的[(+of)]"},
{ en: "As", zh: "[介][副][連]當作、如同"},
{ en: "result", zh: "[vi]發生[名]結果"},
{ en: "many", zh: "[形]許多的"},
{ en: "Norwegians", zh: "挪威人"},
{ en: "use", zh: "[vt]使用"},
{ en: "taxis", zh: "[名]計程車"},
{ en: "drinking", zh: "[vt]喝"},
{ en: "spending", zh: "[vt]花費"},
{ en: "night", zh: "[名]晚上"},
{ en: "on", zh: ""}];