const DA0 = [
{en:" 1. When writing a formal letter, it is better to keep the content ＿ and to the point. (A)succinct　(B)sufficient　(C)supplement　(D)applicable"},
{en:" 2.Purchasing a new apartment is a ＿ decision. We should go through detailed research and discussion before we make the final deal. (A)worthwhile　(B)digital　(C)critical　(D)potential"},
{en:" 3.Unable to deny the evidence pointing to him, the murderer claims that the police ＿ evidence against him. (A)completed　(B)complicated　(C)contemplated　(D)fabricated"},
{en:" 4.In December, the whole city is filled with joyful atmosphere. We were ＿ by the Christmas lights and decorations along the streets. (A)wandered　(B)advocated　(C)enhanced　(D)enchanted"},
{en:" 5.Our company plans to build new factories to accommodate expanding orders. But we still haven't found ideal ＿ for our purpose. (A)libraries　(B)penalties　(C)premises　(D)assemblies"},
{en:" 6.Due to frequently occurred terrorist attack, everyone is required to go through the ＿ check before entering the city hall . (A)conservation　(B)radiation　(C)security　(D)confidential"},
{en:" 7.Jerry is a very ＿ man. He ponders on every possible choice and analyzes its pros and cons before making each decision. (A)sensitive　(B)intrusive　(C)sensible　(D)considerable"}];

const DA2 = [
{zh:"1.【A】撰寫正式書信時，最好能維持內容簡明扼要，並切入重點。(A)簡明扼要　(B)足夠的　(C)補充物　(D)適用的"},
{zh:"2【C】購買新公寓是一個重大的決定，我們應該在做最終買賣前經過詳細的研究和討論。(A)值得的　(B)數位的　(C)重大的　(D)潛在的"},
{zh:"3【D】那位兇手無法否認指向他的證據，便聲稱警方捏造對他不利的證據。(A)完成　(B)複雜的　(C)沉思　(D)捏"},
{zh:"4【D】在十二月份，整座城市都充滿歡樂的氣氛。我們都陶醉於沿路的聖誕燈飾及擺設。(A)遊蕩　(B)提倡　(C)增加　(D)陶醉"},
{zh:"5【C】我們公司計畫要蓋新工廠來容納越來越多的訂單，但我們還沒找到理想的廠址。(A)圖書館　(B)懲罰　(C)廠址　(D)集會"},
{zh:"6【C】因為恐怖攻擊事件頻繁發生，每個人在進入市政廳前都必須通過安全檢查。(A)保育　(B)輻射　(C)安全　(D)機密的"},
{zh:"7【C】Jerry是一個很明智的人，他在做每個決定前都會思考各個可能的選擇並分析其利弊。<BR>(A)敏感的　(B)侵入性的　(C)明智的　(D)相當的"}];

const DA1 = [{ en: "When", zh: "[副][連]pro[名]何時", mp3: "888"},
{ en: "writing", zh: "[名]書寫；寫作", mp3: "12823"},
{ en: "a", zh: "一", mp3: "12715"},
{ en: "formal", zh: "[形]正式的", mp3: "1318"},
{ en: "letter", zh: "[名]信件", mp3: "12841"},
{ en: "it", zh: "它", mp3: "12734"},
{ en: "is", zh: "是", mp3: "12714"},
{ en: "better", zh: "[形]較好的", mp3: "101"},
{ en: "to", zh: "[介]向；往；到", mp3: "820"},
{ en: "keep", zh: "[動]持有，保有", mp3: "12839"},
{ en: "the", zh: "這些，那些", mp3: "12713"},
{ en: "content", zh: "[形]滿足的，滿意的[vt]滿足[名]滿足", mp3: "3324"},
{ en: "and", zh: "[連]和", mp3: "37"},
{ en: "point", zh: "[vi]指向、[名]尖端", mp3: "565"},
{ en: "Purchasing", zh: "[名]購買。[動]purchase的動詞現在分詞、動名詞", mp3: "12854"},
{ en: "new", zh: "[形]新的", mp3: "488"},
{ en: "apartment", zh: "[名]公寓房間", mp3: "962"},
{ en: "decision", zh: "[名]決定", mp3: "1174"},
{ en: "We", zh: "pro[名](主格)我們", mp3: "874"},
{ en: "should", zh: "應該", mp3: ""},
{ en: "go", zh: "[vi]去", mp3: "366"},
{ en: "through", zh: "[介][副]通過", mp3: "1892"},
{ en: "detailed", zh: "[名]細節；詳情", mp3: "2260"},
{ en: "research", zh: "[名][vi][vt](學術)研究；調查，探究", mp3: "4009"},
{ en: "discussion", zh: "[名]討論", mp3: "1205"},
{ en: "before", zh: "[介]在…之前", mp3: "92"},
{ en: "we", zh: "pro[名](主格)我們", mp3: "874"},
{ en: "make", zh: "[vt]做", mp3: "429"},
{ en: "final", zh: "[形]最後的", mp3: "318"},
{ en: "deal", zh: "[vi]處理", mp3: "224"},
{ en: "Unable", zh: "", mp3: "12864"},
{ en: "deny", zh: "[vt]否認", mp3: "1181"},
{ en: "evidence", zh: "[名]證據；證詞；證人；物證", mp3: "3508"},
{ en: "pointing", zh: "[vi]指向、[名]尖端", mp3: "565"},
{ en: "him", zh: "他(受詞)", mp3: "12842"},
{ en: "murderer", zh: "[名]謀殺犯，兇手", mp3: "3820"},
{ en: "claims", zh: "[vt][vi][名]要求", mp3: "1092"},
{ en: "that", zh: "那", mp3: "12753"},
{ en: "police", zh: "[名]警察", mp3: "566"},
{ en: "against", zh: "[介]反對", mp3: "17"},
{ en: "In", zh: "在", mp3: "12717"},
{ en: "December", zh: "[名]十二月(De)", mp3: "227"},
{ en: "whole", zh: "[形]全部的", mp3: "895"},
{ en: "city", zh: "[名]城市", mp3: "178"},
{ en: "filled", zh: "[vt]填滿", mp3: "317"},
{ en: "with", zh: "prpe.與…一起", mp3: "908"},
{ en: "joyful", zh: "[形]高興的，充滿喜悅的", mp3: "2503"},
{ en: "atmosphere", zh: "[名]大氣層；氣氛", mp3: "3182"},
{ en: "were", zh: "is過去式", mp3: "12727"},
{ en: "by", zh: "[介]透過；在…旁邊", mp3: "143"},
{ en: "Christmas", zh: "[名]聖誕節", mp3: "175"},
{ en: "lights", zh: "[名]光[vt][vi]照亮[形]明亮的、[形]淺色的；輕的", mp3: "406"},
{ en: "decorations", zh: "[名]裝飾；裝飾品", mp3: "3382"},
{ en: "along", zh: "[介]沿著", mp3: "31"},
{ en: "streets", zh: "[名]街道", mp3: "763"},
{ en: "Our", zh: "pro[名]我們的(s)", mp3: "527"},
{ en: "company", zh: "[名]公司", mp3: "1118"},
{ en: "plans", zh: "[名]計畫", mp3: "557"},
{ en: "build", zh: "[vt]建造", mp3: "135"},
{ en: "factories", zh: "factory的名詞複數", mp3: "296"},
{ en: "accommodate", zh: "[vt]容納", mp3: "5303"},
{ en: "expanding", zh: "[vt][vi]展開，張開(帆，翅)；使膨脹", mp3: "3516"},
{ en: "orders", zh: "[名]順序", mp3: "525"},
{ en: "But", zh: "[連]但是", mp3: "139"},
{ en: "still", zh: "(1)[形]靜止的、[副]仍舊", mp3: "757"},
{ en: "found", zh: "[vt]建立；創辦", mp3: "2382"},
{ en: "ideal", zh: "[形]理想的[名]理想", mp3: "2462"},
{ en: "for", zh: "[介]為了", mp3: "334"},
{ en: "our", zh: "pro[名]我們的(s)", mp3: "527"},
{ en: "purpose", zh: "[名]目的", mp3: "585"},
{ en: "Due", zh: "[形]到期的；應支付的", mp3: "2292"},
{ en: "frequently", zh: "頻繁地", mp3: "8913"},
{ en: "attack", zh: "[vt][vi]襲擊", mp3: "980"},
{ en: "check", zh: "[vt]檢查", mp3: "170"},
{ en: "entering", zh: "[vt]進入", mp3: "282"},
{ en: "hall", zh: "[名]大廳", mp3: "1364"},
{ en: "very", zh: "[副](1)非常", mp3: "859"},
{ en: "man", zh: "[名]男人", mp3: "430"},
{ en: "He", zh: "[名]他", mp3: "401"},
{ en: "ponders", zh: "[vt][vi]沈思；仔細考慮", mp3: "5995"},
{ en: "on", zh: "", mp3: "12802"},
{ en: "every", zh: "[形]每個", mp3: "287"},
{ en: "possible", zh: "[形]可能的", mp3: "573"},
{ en: "choice", zh: "[名]選擇", mp3: "1087"},
{ en: "analyzes", zh: "分析", mp3: "6630"},
{ en: "its", zh: "它", mp3: "12734"},
{ en: "making", zh: "[動][名]製作、製造", mp3: "12861"},

{en: "succinct", zh: " [形]簡練的；簡潔的" , mp3: "12874" },
{en: "sufficient", zh: " [形]足夠的，充分的" , mp3: "2950" },
{en: "supplement", zh: " [名]增補；補給品" , mp3: "6232" },
{en: "applicable", zh: " [形]適用的" , mp3: "5355" },
{en: "worthwhile", zh: " [形]值得做的" , mp3: "5274" },
{en: "digital", zh: " [形]數位的；數字的。[名]數字顯示式電子表(或鐘)" , mp3: "3417" },
{en: "critical", zh: " [形]緊要的，關鍵危急的；批評的；愛挑剔的" , mp3: "3364" },
{en: "potential", zh: " [形]潛在的" , mp3: "4916" },
{en: "completed", zh: " [形][動]完整(的)" , mp3: "1121" },
{en: "complicated", zh: " [動]使複雜化" , mp3: "3287" },
{en: "contemplated", zh: " [動]深思" , mp3: "4426" },
{en: "fabricated", zh: " [動]製造；組裝；偽造" , mp3: "12720" },
{en: "wandered", zh: " [動][名]漫遊；閒逛" , mp3: "3069" },
{en: "advocated", zh: " [動]提倡" , mp3: "5324" },
{en: "enhanced", zh: " [動]增加(價值,吸引力等)" , mp3: "5663" },
{en: "enchanted", zh: " [形]陶醉的。" , mp3: "12871" },
{en: "libraries", zh: " [名]圖書館" , mp3: "1463" },
{en: "penalties", zh: " 處罰" , mp3: "10532" },
{en: "premises", zh: " [名]房宅、經營場址；premise的名詞複數" , mp3: "12745" },
{en: "assemblies", zh: " [名]集會；集合" , mp3: "3170" },
{en: "conservation", zh: " [名]保育" , mp3: "5498" },
{en: "radiation", zh: " [名]輻射；發光" , mp3: "6045" },
{en: "security", zh: " [名]安全；保安；證券" , mp3: "2848" },
{en: "confidential", zh: " [形]機密的" , mp3: "5490" },
{en: "sensitive", zh: " [形]敏感的；靈敏的" , mp3: "2853" },
{en: "intrusive", zh: " [形][形]dj.侵入的，闖入的；" , mp3: "12750" },
{en: "sensible", zh: " [形]明智的；可注意到的，" , mp3: "2852" },
{en: "considerable", zh: " [形]相當大(多)的" , mp3: "2212" },
{ en: "each", zh: "[形]每個", mp3: "261"}
];